id: A087D090D
title: Concise Seven-Heap Maṇḍala Offering
type: translation
pechas:
- I650F8B9A
- I7E888D54
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:34:54.877744
  last_modified_at: 2023-01-04 12:34:54.877758
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I650F8B9A/1733: 1E86
  I7E888D54/52A2: 1E86
